### ISSUE TITLE
week2/exercise0.py add_1 function already complete

### ISSUE THREAD

**Issue by AidenRay** [Design-Computing/me#1]
@notionparallax is this on purpose to show how it works?

**Comment by BaptisteHiggs** [comment]
Yeah it says that it's supposed to be like that in the function's docstring:

```
Return a number that is 1 bigger than number given.

This isn't a trick!

This is an example function to get you started. 
Run the tests now and this one should go green. Free marks!
```

**Comment by BaptisteHiggs** [comment]
Looks like @notionparallax is the only one who can close issues (that aren't his own)

**Comment by AidenRay** [comment]
Hmm, probably smart to read the doc string...
