### ISSUE TITLE
week3/_init_.py exists but is empty?

### ISSUE THREAD

**Issue by BaptisteHiggs** [Design-Computing/me#2]
Unsure if this is necessary for some reason so I won't include it in my eventual PR but thought I'd bring it up.

Also setup.py in the same folder, seems to be code that's supposed to be imported, but it isn't imported anywhere in the week 3 folder?

**Comment by notionparallax** [comment]
An empty _init_.py signals that you are intending that to be the case. TBH, I'm not really sure how it works, I understood when I put it in, but that was a long time ago

I've removed that folder from week 3. It pip installed a library, I've moved the installation to `requirements.txt`
