### ISSUE TITLE
Socket Issue with Debugging

### ISSUE THREAD

**Issue by Brightonjake** [Design-Computing/me#6]
<img width="1680" alt="Screen Shot 2019-06-07 at 1 55 51 pm" src="https://user-images.githubusercontent.com/51425870/59080447-137c7280-892c-11e9-9afa-0849cad05e39.png">

**Comment by notionparallax** [comment]
@Brightonjake do you think that this is closed now?

**Comment by Brightonjake** [comment]
@notionparallax the debugger is now working on VScode however tests do not. However I can get tests to run on terminal so should be fine.

**Comment by notionparallax** [comment]
aged out
